Add blog/2023-02-19-yw2446.md
intricatecloud/cs5356-docs pull request #153
Opened 2023-02-20 03:25 UTC by yiwen5

2023-02-20 15:40 UTC, intricatecloud approved these changes

2023-02-20 15:42 UTC, intricatecloud requested changes
hi @yiwen5 - this PR is showing that the filename is `blog:2023...` with a colon in the middle. The filename should be `blog/2023...` with a `/` character instead of the colon. Can you update that on this PR?

2023-02-21 13:26 UTC, yiwen5 commented
> hi @yiwen5 - this PR is showing that the filename is `blog:2023...` with a colon in the middle. The filename should be `blog/2023...` with a `/` character instead of the colon. Can you update that on this PR?

Hi, I have already fixed that. Thank you.

2023-02-23 19:49 UTC, intricatecloud approved these changes

2023-02-23 19:49 UTC, merged